version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
jobs:
  build-job:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: show directory 
          command: pwd
      - run:
          name: look in directory
          command: ls -ltr
      - run: 
          name: Install dependencies
          command: npm install
      - run: 
          name: Build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:unit

  deploy-job:
    working_directory: ~/project
    docker: 
      - image: circleci/node:12.18.2
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      # - attach_workspace:
      #     at: ~/project
      - run:
          name: show directory 
          command: pwd
      - run:
          name: look in directory
          command: ls -ltr
      - heroku/deploy-via-git

workflows:
  # version: 2.1
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
