version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5 # Use the Heroku orb in your config

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch

# version: 2.1
# orbs:
#   heroku: circleci/heroku@1.2.5
# jobs:
#   build-job:
#     working_directory: ~/repo
#     docker:
#       - image: circleci/node:12.18.2
#     steps:
#       - checkout
#       # - restore_cache:
#       #     key: dependency-cache-{{ checksum "package-lock.json" }}
#       - run: 
#           name: Install dependencies
#           command: npm install
#       - run: 
#           name: Build
#           command: npm run build
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: lint
#           command: npm run lint
#       - run:
#           name: test
#           command: npm run test:unit

#   deploy-job:
#     working_directory: ~/repo
#     docker: 
#       - image: circleci/node:12.18.2
#     steps:
#       # - restore_cache:
#       #     key: dependency-cache-{{ checksum "package-lock.json" }}
#       - attach_workspace:
#           at: ~/repo
#       - heroku/deploy-via-git

# workflows:
#   version: 2.1
#   deploy:
#     jobs:
#       - build-job
#       - deploy-job:
#           requires:
#             - build-job
#           filters:
#             branches:
#               only: master
